name: TileDB Python and C++ Linting

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/python
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: Check Python Black Format
        run: |
          python -m pip install black
          python -m black --check --diff . tools/[a-z]*

      - name: Check for unsorted / unformatted Python imports with isort
        run: |
          python -m pip install isort
          python -m isort --check --diff .

      - name: Check Python style guide enforcement with flake8
        run: |
          python -m pip install flake8-bugbear
          python -m flake8 . tools/[a-z]*

      - name: Check type annotations with mypy
        run: |
          # mypy 0.990 has false positives on `import anndata as ad` and `Module has no attribute
          # "read_h5ad"` etc :(
          # python -m pip install mypy types-setuptools typeguard
          python -m pip install mypy==0.982 types-setuptools typeguard 'attrs>=22.1'
          python -m mypy .

      - name: Check C++ Format
        run: |
          cd ../..
          ./scripts/run-clang-format.sh . clang-format 0 \
            $(find libtiledbsoma -name "*.cc" -or -name "*.h")
