# Reusable workflow that runs Python tests.
# About reusable workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow

name: TileDB-SOMA Python CI

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      os:
        required: true
        type: string
      cc:
        required: false
        type: string
      cxx:
        required: false
        type: string
      report_codecov:
        required: true
        type: boolean
      extra_pytest_options:
        required: false
        type: string

jobs:

  pytest:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Show matrix OS
        run: echo "inputs.os:" ${{ inputs.os }}

      - name: Linux CPU info
        if: ${{ startsWith(inputs.os, 'ubuntu-') == true }}
        run: cat /proc/cpuinfo

      - name: MacOS CPU info
        if: ${{ startsWith(inputs.os, 'macos-') == true }}
        run: sysctl -a | grep cpu

      - name: "Setup system dependencies on Linux"
        if: ${{ startsWith(inputs.os, 'ubuntu-') == true }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build pkg-config autoconf automake libtool

      - name: "Brew setup on macOS"
        if: ${{ startsWith(inputs.os, 'macos-') == true }}
        run: |
          set -e pipefail
          brew update
          brew install automake llvm ninja

      - name: Checkout TileDB-SOMA
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to fetch tags: https://github.com/actions/checkout/issues/2199
          fetch-tags: true  # Tags used for Python package version.

      - name: Checkout vcpkg
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - name: Bootstrap vcpkg
        run: |
          ./vcpkg/bootstrap-vcpkg.sh
          echo "CMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV
          echo "VCPKG_ROOT=${{ github.workspace }}/vcpkg" >> $GITHUB_ENV

      - name: Set vcpkg triplet
        run: |
          if [[ "${{ inputs.os }}" == *"ubuntu"* ]]; then
            echo "VCPKG_TARGET_TRIPLET=x64-linux-release" >> $GITHUB_ENV
          elif [[ "${{ inputs.os }}" == *"macos"* ]]; then
            arch=$(uname -m)
            if [ "$arch" = "arm64" ]; then
              echo "VCPKG_TARGET_TRIPLET=arm64-osx-release" >> $GITHUB_ENV
              echo "CMAKE_OSX_ARCHITECTURES=arm64" >> $GITHUB_ENV
            else
              echo "VCPKG_TARGET_TRIPLET=x64-osx-release" >> $GITHUB_ENV
              echo "CMAKE_OSX_ARCHITECTURES=x86_64" >> $GITHUB_ENV
            fi
          fi

      - name: Download pre-built C++ library
        uses: actions/download-artifact@v4
        with:
          name: cpp-build-Release-${{ inputs.os }}

      - name: Set up test data
        run: make data

      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
          cache: pip
          cache-dependency-path: ./apis/python/pyproject.toml

      - name: Install tiledbsoma
        run: pip -v install -e apis/python[all]
        env:
          CC: ${{ inputs.cc }}
          CXX: ${{ inputs.cxx }}

      - name: Show package versions
        run: python scripts/show-versions.py

      - name: Log pip dependencies
        run: pip list

      - name: Run pytests for Python
        shell: bash
        # Setting PYTHONPATH ensures the tests load the in-tree source code under apis/python/src
        # instead of the copy we `pip install`ed to site-packages above. That's needed for the code
        # coverage analysis to work.
        run: PYTHONPATH=$(pwd)/apis/python/src python -m pytest --cov=apis/python/src --cov-report=xml apis/python/tests -v --durations=20 --maxfail=50 ${{ inputs.extra_pytest_options }}

      - name: Report coverage to Codecov
        if: inputs.report_codecov
        uses: codecov/codecov-action@v5
        with:
          flags: python
          # Although Codecov isn't supposed to require an auth token for public repos like this one,
          # the uploader can be unreliable without one; see
          #     https://github.com/codecov/codecov-action/issues/557#issuecomment-1216749652
          # As of this writing (8 Nov 2022) the CODECOV_TOKEN was generated by @aaronwolen in his
          # Codecov settings page for this repo, then filled into the GitHub Actions secrets.
          token: ${{ secrets.CODECOV_TOKEN }}
